FROM registry.access.redhat.com/rhel8/skopeo
# FROM registry.access.redhat.com/ubi8/openjdk-17
# RUN yum update -y
# FROM registry.access.redhat.com/ubi8:8.0
CMD bash -c "while true; do echo sleeping; sleep 5; done"
